openapi: 3.0.0
info:
  title: GitHub Branch Protection Configuration
  version: 1.0.0
  description: Schema for branch protection rule configuration via GitHub API

paths:
  /repos/{owner}/{repo}/branches/{branch}/protection:
    put:
      summary: Configure branch protection rules
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: repo
          in: path
          required: true
          schema:
            type: string
        - name: branch
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BranchProtectionRule'

components:
  schemas:
    BranchProtectionRule:
      type: object
      required:
        - required_status_checks
        - required_pull_request_reviews
        - restrictions
      properties:
        required_status_checks:
          type: object
          required:
            - strict
            - contexts
          properties:
            strict:
              type: boolean
              description: Require branches to be up to date before merging
              default: true
            contexts:
              type: array
              description: List of required status check names
              items:
                type: string
              example:
                - "build-and-test"
                - "security-scan-codeql"
                - "dependency-check"
                - "code-coverage"
                - "lint-validation"
        required_pull_request_reviews:
          type: object
          required:
            - required_approving_review_count
          properties:
            required_approving_review_count:
              type: integer
              minimum: 1
              maximum: 6
              description: Number of required approving reviews
              default: 1
            require_code_owner_reviews:
              type: boolean
              description: Require review from code owners
              default: true
            dismiss_stale_reviews:
              type: boolean
              description: Dismiss stale reviews when new commits are pushed
              default: true
            restricts_review_dismissals:
              type: object
              properties:
                users:
                  type: array
                  items:
                    type: string
                teams:
                  type: array
                  items:
                    type: string
        restrictions:
          type: object
          nullable: true
          properties:
            users:
              type: array
              description: Users with push access
              items:
                type: string
            teams:
              type: array
              description: Teams with push access
              items:
                type: string
            apps:
              type: array
              description: Apps with push access
              items:
                type: string
        enforce_admins:
          type: boolean
          description: Enforce all configured restrictions for administrators
          default: true
        allow_force_pushes:
          type: boolean
          description: Allow force pushes to the branch
          default: false
        allow_deletions:
          type: boolean
          description: Allow deletion of the branch
          default: false
        required_linear_history:
          type: boolean
          description: Require linear history
          default: true